name: smartrent_mobile
description: SmartRent mobile app - blockchain-enabled rental and asset-sharing platform

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.1
  
  # HTTP Client and API
  http: ^1.1.0
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Web3 and Blockchain (commented out for now, using mock service)
  # web3dart: ^3.1.5
  # walletconnect_flutter_v2: ^2.1.12
  
  # UI Components and Utils
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  
  # Forms and Validation
  flutter_form_builder: ^9.1.1
  # form_builder_validators: ^9.1.0 # Commented out due to intl conflicts
  
  # Date and Time
  intl: any
  timeago: ^3.6.0
  
  # Images and Media
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Permissions
  permission_handler: ^11.0.1
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Biometric Authentication
  local_auth: ^2.1.6
  
  # Utils
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.1
  
  # Loading and Progress
  loading_animation_widget: ^1.2.0+4
  
  # Toast and Snackbars
  fluttertoast: ^8.2.4
  
  # Crypto and Security
  crypto: ^3.0.3
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets (commented - will be created later)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/

  # Fonts (commented - will be created later)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Roboto-Light.ttf
  #         weight: 300









